# Generated by Django 5.2 on 2025-04-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilusuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='avatar_default',
            field=models.CharField(blank=True, choices=[('avatar_male.png', 'Avatar masculino'), ('avatar_female.png', 'Avatar femenino'), ('avatar_old.png', 'Avatar anciano'), ('avatar_child.png', 'Avatar infantil')], help_text='Puedes elegir un avatar predeterminado si no deseas subir una imagen propia.', max_length=100, null=True),
        ),
    ]
